name = "url-shortener"
compatibility_date = "2024-04-11"
workers_dev = false
main = "src/index.ts"

kv_namespaces = [
  { binding = "URL_MAPPINGS", id = "" },
  { binding = "URL_ANALYTICS", id = "" },
  { binding = "API_KEYS", id = "" },
  { binding = "CUSTOM_DOMAINS", id = "" },
  { binding = "OG_METADATA_CACHE", id = "" }
]

[vars]
REDIRECT_URL = ""
ALLOWED_CORS_ORIGINS = ""

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"